# Fixtures and expected results are generated by SimpleITK, independently of R.
# See tools/generate_itk_oracle.py and inst/extdata/itk_oracle/README.md.
itk_oracle <- function(name) {
  system.file("extdata", "itk_oracle", name, package = "neurotransform",
              mustWork = TRUE)
}

test_that("ITK affine formats and both H5 orders reproduce independent points", {
  skip_if_not_installed("hdf5r")
  skip_if_not_installed("jsonlite")
  oracle <- jsonlite::fromJSON(itk_oracle("evidence.json"))
  for (reader in list(function(p) read_transform(p, type = "ants_h5"), ants_h5_morphism)) {
    affine_only <- reader(itk_oracle("affine.h5"))
    expect_s4_class(affine_only, "Affine3DMorphism")
    expect_lt(max(abs(transform(affine_only, oracle$points_ras)-oracle$expected_ras$affine)), 1e-9)
  }
  expect_error(ants_h5_morphism(itk_oracle("affine.h5"), apply_affine = FALSE), "no displacement")
  for (suffix in c("tfm", "mat", "h5")) {
    m <- read_linear_transform(itk_oracle(paste0("affine.", suffix)), format = "itk")
    expect_lt(max(abs(transform(m, oracle$points_ras) - oracle$expected_ras$affine)), 1e-9)
  }
  for (name in c("affine_warp", "warp_affine")) {
    m <- read_transform(itk_oracle(paste0(name, ".h5")))
    expect_lt(max(abs(transform(m, oracle$points_ras) - oracle$expected_ras[[name]])), 1e-9)
  }
  m <- read_transform(itk_oracle("warp.nii.gz"), type = "ants")
  expect_lt(max(abs(transform(m, oracle$points_ras) - oracle$expected_ras$warp)), 2e-6)
})

test_that("H5 resampling reproduces SimpleITK interior intensities in both orders", {
  skip_if_not_installed("hdf5r")
  source <- neuroim2::read_vol(itk_oracle("source.nii.gz"))
  for (name in c("affine_warp", "warp_affine")) {
    m <- read_transform(itk_oracle(paste0(name, ".h5")))
    actual <- as.array(resample_to(source, source, m, method = "linear"))
    expected <- as.array(neuroim2::read_vol(itk_oracle(paste0(name, "_resampled.nii.gz"))))
    # Exclude the image boundary, whose padding rules are a separate contract.
    expect_lt(max(abs(actual[2:6, 2:7, 2:8] - expected[2:6, 2:7, 2:8])), 2e-5)
  }
})

test_that("cubic warp interpolation preserves a multilinear vector field", {
  skip_if_not_installed("jsonlite")
  oracle <- jsonlite::fromJSON(itk_oracle("evidence.json"))
  m <- read_transform(itk_oracle("warp.nii.gz"), type = "ants")
  m@params$warp_method <- "cubic"
  # This polynomial is reproduced exactly by both linear and Catmull-Rom
  # interpolation at interior points; the three components are distinct.
  expect_lt(max(abs(transform(m, oracle$points_ras) - oracle$expected_ras$warp)), 2e-6)
})

test_that("warp exports have the ANTs vector layout and preserve RAS geometry", {
  skip_if_not_installed("RNifti")
  m <- read_transform(itk_oracle("warp.nii.gz"), type = "ants")
  path <- tempfile(fileext = ".nii.gz")
  on.exit(unlink(path))
  write_warp_field(m, path)
  header <- RNifti::niftiHeader(path)
  expect_equal(header$dim, c(5, 7, 8, 9, 1, 3, 1, 1))
  expect_equal(header$intent_code, 1007)
  expect_equal(unname(RNifti::xform(path)), unname(RNifti::xform(itk_oracle("warp.nii.gz"))),
               ignore_attr = TRUE, tolerance = 2e-6)
  # Raw data compare catches a shared sign error in our reader and writer.
  expect_equal(as.numeric(RNifti::readNifti(path)),
               as.numeric(RNifti::readNifti(itk_oracle("warp.nii.gz"))), tolerance = 1e-7)
})

test_that("warp exports convert absolute and relative representations on signed grids", {
  skip_if_not_installed("RNifti")
  dims <- c(3L, 4L, 5L)
  ijk <- as.matrix(expand.grid(0:2, 0:3, 0:4))
  displacement <- matrix(rep(c(.25, -.5, .75), each = nrow(ijk)), ncol = 3)
  path <- tempfile(fileext = ".nii.gz")
  on.exit(unlink(path))
  for (sign in c(-1, 1)) {
    affine <- diag(c(sign * 1.3, 1.7, 2.1, 1))
    affine[1:3, 4] <- c(12, -8, 3)
    world <- (cbind(ijk, 1) %*% t(affine))[, 1:3]
    for (native in c("displacements", "deformations")) {
      values <- if (native == "displacements") displacement else world + displacement
      m <- warp_from_field("s", "t", array(values, c(dims, 3)),
                           grid = grid_spec(dims, affine), representation = native)
      for (output in c("auto", "displacements", "deformations")) {
        representation <- if (output == "auto") native else output
        expected <- if (representation == "displacements") displacement else world + displacement
        expected_lps <- sweep(expected, 2, c(-1, -1, 1), "*")
        write_warp_field(m, path, representation = output)
        expect_lt(max(abs(as.numeric(RNifti::readNifti(path)) - as.numeric(expected_lps))), 2e-6)
        expect_equal(RNifti::xform(path), affine, ignore_attr = TRUE, tolerance = 2e-6)
      }
    }
  }
})
