// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_apply_projector
Rcpp::NumericMatrix cpp_apply_projector(const Rcpp::S4& projMat, const Rcpp::NumericMatrix& data, int threads);
RcppExport SEXP _neurotransform_cpp_apply_projector(SEXP projMatSEXP, SEXP dataSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type projMat(projMatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_apply_projector(projMat, data, threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_apply_affine_chain
Rcpp::NumericMatrix cpp_apply_affine_chain(const Rcpp::NumericMatrix& coords, const Rcpp::List& matrices);
RcppExport SEXP _neurotransform_cpp_apply_affine_chain(SEXP coordsSEXP, SEXP matricesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type matrices(matricesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_apply_affine_chain(coords, matrices));
    return rcpp_result_gen;
END_RCPP
}
// cpp_barycentric_weights
Rcpp::List cpp_barycentric_weights(const Rcpp::NumericMatrix& coords, const Rcpp::NumericMatrix& vertices, const Rcpp::IntegerMatrix& faces);
RcppExport SEXP _neurotransform_cpp_barycentric_weights(SEXP coordsSEXP, SEXP verticesSEXP, SEXP facesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type faces(facesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_barycentric_weights(coords, vertices, faces));
    return rcpp_result_gen;
END_RCPP
}
// cpp_warp_jacobian
Rcpp::NumericVector cpp_warp_jacobian(const Rcpp::NumericMatrix& coords, const Rcpp::NumericVector& field, const Rcpp::IntegerVector& dim, const Rcpp::NumericMatrix& world_to_vox, const Rcpp::NumericMatrix& vox_to_world);
RcppExport SEXP _neurotransform_cpp_warp_jacobian(SEXP coordsSEXP, SEXP fieldSEXP, SEXP dimSEXP, SEXP world_to_voxSEXP, SEXP vox_to_worldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type field(fieldSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type world_to_vox(world_to_voxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type vox_to_world(vox_to_worldSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_warp_jacobian(coords, field, dim, world_to_vox, vox_to_world));
    return rcpp_result_gen;
END_RCPP
}
// cpp_warp_jacobian_cubic
Rcpp::NumericVector cpp_warp_jacobian_cubic(const Rcpp::NumericMatrix& coords, const Rcpp::NumericVector& field, const Rcpp::IntegerVector& dim, const Rcpp::NumericMatrix& world_to_vox, const Rcpp::NumericMatrix& vox_to_world);
RcppExport SEXP _neurotransform_cpp_warp_jacobian_cubic(SEXP coordsSEXP, SEXP fieldSEXP, SEXP dimSEXP, SEXP world_to_voxSEXP, SEXP vox_to_worldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type field(fieldSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type world_to_vox(world_to_voxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type vox_to_world(vox_to_worldSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_warp_jacobian_cubic(coords, field, dim, world_to_vox, vox_to_world));
    return rcpp_result_gen;
END_RCPP
}
// cpp_warp_jacobian_det_cubic
Rcpp::NumericVector cpp_warp_jacobian_det_cubic(const Rcpp::NumericMatrix& coords, const Rcpp::NumericVector& field, const Rcpp::IntegerVector& dim, const Rcpp::NumericMatrix& world_to_vox, const Rcpp::NumericMatrix& vox_to_world);
RcppExport SEXP _neurotransform_cpp_warp_jacobian_det_cubic(SEXP coordsSEXP, SEXP fieldSEXP, SEXP dimSEXP, SEXP world_to_voxSEXP, SEXP vox_to_worldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type field(fieldSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type world_to_vox(world_to_voxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type vox_to_world(vox_to_worldSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_warp_jacobian_det_cubic(coords, field, dim, world_to_vox, vox_to_world));
    return rcpp_result_gen;
END_RCPP
}
// cpp_warp_jacobian_det
Rcpp::NumericVector cpp_warp_jacobian_det(const Rcpp::NumericMatrix& coords, const Rcpp::NumericVector& field, const Rcpp::IntegerVector& dim, const Rcpp::NumericMatrix& world_to_vox, const Rcpp::NumericMatrix& vox_to_world);
RcppExport SEXP _neurotransform_cpp_warp_jacobian_det(SEXP coordsSEXP, SEXP fieldSEXP, SEXP dimSEXP, SEXP world_to_voxSEXP, SEXP vox_to_worldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type field(fieldSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type world_to_vox(world_to_voxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type vox_to_world(vox_to_worldSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_warp_jacobian_det(coords, field, dim, world_to_vox, vox_to_world));
    return rcpp_result_gen;
END_RCPP
}
// cpp_path_apply_affine_warp
Rcpp::NumericMatrix cpp_path_apply_affine_warp(const Rcpp::NumericMatrix& coords, const Rcpp::List& affines, const Rcpp::NumericVector& field, const Rcpp::IntegerVector& dim, const Rcpp::NumericMatrix& world_to_vox, bool cubic);
RcppExport SEXP _neurotransform_cpp_path_apply_affine_warp(SEXP coordsSEXP, SEXP affinesSEXP, SEXP fieldSEXP, SEXP dimSEXP, SEXP world_to_voxSEXP, SEXP cubicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type affines(affinesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type field(fieldSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type world_to_vox(world_to_voxSEXP);
    Rcpp::traits::input_parameter< bool >::type cubic(cubicSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_path_apply_affine_warp(coords, affines, field, dim, world_to_vox, cubic));
    return rcpp_result_gen;
END_RCPP
}
// cpp_path_apply_affine_warp_affine
Rcpp::NumericMatrix cpp_path_apply_affine_warp_affine(const Rcpp::NumericMatrix& coords, const Rcpp::List& affines_pre, const Rcpp::NumericVector& field, const Rcpp::IntegerVector& dim, const Rcpp::NumericMatrix& world_to_vox, bool cubic, const Rcpp::List& affines_post);
RcppExport SEXP _neurotransform_cpp_path_apply_affine_warp_affine(SEXP coordsSEXP, SEXP affines_preSEXP, SEXP fieldSEXP, SEXP dimSEXP, SEXP world_to_voxSEXP, SEXP cubicSEXP, SEXP affines_postSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type affines_pre(affines_preSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type field(fieldSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type world_to_vox(world_to_voxSEXP);
    Rcpp::traits::input_parameter< bool >::type cubic(cubicSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type affines_post(affines_postSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_path_apply_affine_warp_affine(coords, affines_pre, field, dim, world_to_vox, cubic, affines_post));
    return rcpp_result_gen;
END_RCPP
}
// cpp_path_apply_steps
Rcpp::NumericMatrix cpp_path_apply_steps(const Rcpp::NumericMatrix& coords, const Rcpp::List& steps);
RcppExport SEXP _neurotransform_cpp_path_apply_steps(SEXP coordsSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type steps(stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_path_apply_steps(coords, steps));
    return rcpp_result_gen;
END_RCPP
}
// cpp_make_resample_plan
SEXP cpp_make_resample_plan(const Rcpp::IntegerVector& src_dim, const Rcpp::NumericMatrix& src_coords_vox, const std::string& method);
RcppExport SEXP _neurotransform_cpp_make_resample_plan(SEXP src_dimSEXP, SEXP src_coords_voxSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type src_dim(src_dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type src_coords_vox(src_coords_voxSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_make_resample_plan(src_dim, src_coords_vox, method));
    return rcpp_result_gen;
END_RCPP
}
// cpp_apply_resample_plan
Rcpp::NumericVector cpp_apply_resample_plan(SEXP plan_xptr, const Rcpp::NumericVector& data, double outside);
RcppExport SEXP _neurotransform_cpp_apply_resample_plan(SEXP plan_xptrSEXP, SEXP dataSEXP, SEXP outsideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type plan_xptr(plan_xptrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type outside(outsideSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_apply_resample_plan(plan_xptr, data, outside));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ribbon_weights
Rcpp::List cpp_ribbon_weights(const Rcpp::NumericMatrix& inner, const Rcpp::NumericMatrix& outer, const Rcpp::NumericMatrix& world_to_vox, const Rcpp::IntegerVector& dims, int n_steps, const Rcpp::LogicalVector& mask);
RcppExport SEXP _neurotransform_cpp_ribbon_weights(SEXP innerSEXP, SEXP outerSEXP, SEXP world_to_voxSEXP, SEXP dimsSEXP, SEXP n_stepsSEXP, SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type inner(innerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type outer(outerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type world_to_vox(world_to_voxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector& >::type mask(maskSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ribbon_weights(inner, outer, world_to_vox, dims, n_steps, mask));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sample_volume
Rcpp::NumericVector cpp_sample_volume(const Rcpp::NumericVector& data, const Rcpp::NumericMatrix& coords, const Rcpp::NumericMatrix& world_to_vox, const std::string& method, double outside);
RcppExport SEXP _neurotransform_cpp_sample_volume(SEXP dataSEXP, SEXP coordsSEXP, SEXP world_to_voxSEXP, SEXP methodSEXP, SEXP outsideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type world_to_vox(world_to_voxSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type outside(outsideSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sample_volume(data, coords, world_to_vox, method, outside));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nearest_vertex
Rcpp::IntegerVector cpp_nearest_vertex(const Rcpp::NumericMatrix& coords, const Rcpp::NumericMatrix& vertices);
RcppExport SEXP _neurotransform_cpp_nearest_vertex(SEXP coordsSEXP, SEXP verticesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type vertices(verticesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nearest_vertex(coords, vertices));
    return rcpp_result_gen;
END_RCPP
}
// cpp_barycentric_sample
Rcpp::NumericVector cpp_barycentric_sample(const Rcpp::NumericMatrix& coords, const Rcpp::NumericMatrix& vertices, const Rcpp::IntegerMatrix& faces, const Rcpp::NumericVector& data);
RcppExport SEXP _neurotransform_cpp_barycentric_sample(SEXP coordsSEXP, SEXP verticesSEXP, SEXP facesSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type faces(facesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_barycentric_sample(coords, vertices, faces, data));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ribbon_sample_volume
Rcpp::NumericVector cpp_ribbon_sample_volume(const Rcpp::NumericVector& data, const Rcpp::NumericMatrix& inner, const Rcpp::NumericMatrix& outer, const Rcpp::NumericMatrix& world_to_vox, int n_steps, const std::string& method);
RcppExport SEXP _neurotransform_cpp_ribbon_sample_volume(SEXP dataSEXP, SEXP innerSEXP, SEXP outerSEXP, SEXP world_to_voxSEXP, SEXP n_stepsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type inner(innerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type outer(outerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type world_to_vox(world_to_voxSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ribbon_sample_volume(data, inner, outer, world_to_vox, n_steps, method));
    return rcpp_result_gen;
END_RCPP
}
// cpp_triplets_to_dgC
Rcpp::S4 cpp_triplets_to_dgC(const Rcpp::IntegerVector& i, const Rcpp::IntegerVector& j, const Rcpp::NumericVector& x, int nrow, int ncol, int threads);
RcppExport SEXP _neurotransform_cpp_triplets_to_dgC(SEXP iSEXP, SEXP jSEXP, SEXP xSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type i(iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type j(jSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_triplets_to_dgC(i, j, x, nrow, ncol, threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_apply_warp_field
Rcpp::NumericMatrix cpp_apply_warp_field(const Rcpp::NumericMatrix& coords, const Rcpp::NumericVector& field, const Rcpp::IntegerVector& dim, const Rcpp::NumericMatrix& voxel_to_world);
RcppExport SEXP _neurotransform_cpp_apply_warp_field(SEXP coordsSEXP, SEXP fieldSEXP, SEXP dimSEXP, SEXP voxel_to_worldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type field(fieldSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type voxel_to_world(voxel_to_worldSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_apply_warp_field(coords, field, dim, voxel_to_world));
    return rcpp_result_gen;
END_RCPP
}
// cpp_apply_warp_field_cubic
Rcpp::NumericMatrix cpp_apply_warp_field_cubic(const Rcpp::NumericMatrix& coords, const Rcpp::NumericVector& field, const Rcpp::IntegerVector& dim, const Rcpp::NumericMatrix& voxel_to_world);
RcppExport SEXP _neurotransform_cpp_apply_warp_field_cubic(SEXP coordsSEXP, SEXP fieldSEXP, SEXP dimSEXP, SEXP voxel_to_worldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type field(fieldSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type voxel_to_world(voxel_to_worldSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_apply_warp_field_cubic(coords, field, dim, voxel_to_world));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compose_warp_fields
Rcpp::List cpp_compose_warp_fields(const Rcpp::NumericVector& fieldA, const Rcpp::IntegerVector& dimA, const Rcpp::NumericMatrix& world_to_voxA, const Rcpp::NumericVector& fieldB, const Rcpp::IntegerVector& dimB, const Rcpp::NumericMatrix& vox_to_worldB);
RcppExport SEXP _neurotransform_cpp_compose_warp_fields(SEXP fieldASEXP, SEXP dimASEXP, SEXP world_to_voxASEXP, SEXP fieldBSEXP, SEXP dimBSEXP, SEXP vox_to_worldBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type fieldA(fieldASEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dimA(dimASEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type world_to_voxA(world_to_voxASEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type fieldB(fieldBSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dimB(dimBSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type vox_to_worldB(vox_to_worldBSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compose_warp_fields(fieldA, dimA, world_to_voxA, fieldB, dimB, vox_to_worldB));
    return rcpp_result_gen;
END_RCPP
}
// cpp_absolute_to_displacement
Rcpp::NumericVector cpp_absolute_to_displacement(const Rcpp::NumericVector& field_abs, const Rcpp::IntegerVector& dim, const Rcpp::NumericMatrix& vox_to_world);
RcppExport SEXP _neurotransform_cpp_absolute_to_displacement(SEXP field_absSEXP, SEXP dimSEXP, SEXP vox_to_worldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type field_abs(field_absSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type vox_to_world(vox_to_worldSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_absolute_to_displacement(field_abs, dim, vox_to_world));
    return rcpp_result_gen;
END_RCPP
}
// cpp_trilinear_weights
Rcpp::List cpp_trilinear_weights(const Rcpp::NumericMatrix& vox_coords, const Rcpp::IntegerVector& dims);
RcppExport SEXP _neurotransform_cpp_trilinear_weights(SEXP vox_coordsSEXP, SEXP dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type vox_coords(vox_coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dims(dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_trilinear_weights(vox_coords, dims));
    return rcpp_result_gen;
END_RCPP
}
// cpp_volume_world_coords
Rcpp::NumericMatrix cpp_volume_world_coords(const Rcpp::IntegerVector& dim, const Rcpp::NumericMatrix& affine);
RcppExport SEXP _neurotransform_cpp_volume_world_coords(SEXP dimSEXP, SEXP affineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type affine(affineSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_volume_world_coords(dim, affine));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_neurotransform_cpp_apply_projector", (DL_FUNC) &_neurotransform_cpp_apply_projector, 3},
    {"_neurotransform_cpp_apply_affine_chain", (DL_FUNC) &_neurotransform_cpp_apply_affine_chain, 2},
    {"_neurotransform_cpp_barycentric_weights", (DL_FUNC) &_neurotransform_cpp_barycentric_weights, 3},
    {"_neurotransform_cpp_warp_jacobian", (DL_FUNC) &_neurotransform_cpp_warp_jacobian, 5},
    {"_neurotransform_cpp_warp_jacobian_cubic", (DL_FUNC) &_neurotransform_cpp_warp_jacobian_cubic, 5},
    {"_neurotransform_cpp_warp_jacobian_det_cubic", (DL_FUNC) &_neurotransform_cpp_warp_jacobian_det_cubic, 5},
    {"_neurotransform_cpp_warp_jacobian_det", (DL_FUNC) &_neurotransform_cpp_warp_jacobian_det, 5},
    {"_neurotransform_cpp_path_apply_affine_warp", (DL_FUNC) &_neurotransform_cpp_path_apply_affine_warp, 6},
    {"_neurotransform_cpp_path_apply_affine_warp_affine", (DL_FUNC) &_neurotransform_cpp_path_apply_affine_warp_affine, 7},
    {"_neurotransform_cpp_path_apply_steps", (DL_FUNC) &_neurotransform_cpp_path_apply_steps, 2},
    {"_neurotransform_cpp_make_resample_plan", (DL_FUNC) &_neurotransform_cpp_make_resample_plan, 3},
    {"_neurotransform_cpp_apply_resample_plan", (DL_FUNC) &_neurotransform_cpp_apply_resample_plan, 3},
    {"_neurotransform_cpp_ribbon_weights", (DL_FUNC) &_neurotransform_cpp_ribbon_weights, 6},
    {"_neurotransform_cpp_sample_volume", (DL_FUNC) &_neurotransform_cpp_sample_volume, 5},
    {"_neurotransform_cpp_nearest_vertex", (DL_FUNC) &_neurotransform_cpp_nearest_vertex, 2},
    {"_neurotransform_cpp_barycentric_sample", (DL_FUNC) &_neurotransform_cpp_barycentric_sample, 4},
    {"_neurotransform_cpp_ribbon_sample_volume", (DL_FUNC) &_neurotransform_cpp_ribbon_sample_volume, 6},
    {"_neurotransform_cpp_triplets_to_dgC", (DL_FUNC) &_neurotransform_cpp_triplets_to_dgC, 6},
    {"_neurotransform_cpp_apply_warp_field", (DL_FUNC) &_neurotransform_cpp_apply_warp_field, 4},
    {"_neurotransform_cpp_apply_warp_field_cubic", (DL_FUNC) &_neurotransform_cpp_apply_warp_field_cubic, 4},
    {"_neurotransform_cpp_compose_warp_fields", (DL_FUNC) &_neurotransform_cpp_compose_warp_fields, 6},
    {"_neurotransform_cpp_absolute_to_displacement", (DL_FUNC) &_neurotransform_cpp_absolute_to_displacement, 3},
    {"_neurotransform_cpp_trilinear_weights", (DL_FUNC) &_neurotransform_cpp_trilinear_weights, 2},
    {"_neurotransform_cpp_volume_world_coords", (DL_FUNC) &_neurotransform_cpp_volume_world_coords, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_neurotransform(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
