# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Apply sparse projector matrix to data
#'
#' Fast C++ sparse matrix multiplication.
#'
#' @param projMat dgCMatrix sparse projector
#' @param data Numeric matrix of data
#' @param threads Number of OpenMP threads
#' @return Projected data matrix
#' @keywords internal
NULL

cpp_apply_projector <- function(projMat, data, threads = 1L) {
    .Call(`_neurotransform_cpp_apply_projector`, projMat, data, threads)
}

#' Apply chain of affine transformations to coordinates
#'
#' Efficiently applies multiple 4x4 affine matrices to coordinates.
#'
#' @param coords Numeric matrix (N x 3) of coordinates
#' @param matrices List of 4x4 affine matrices
#' @return Transformed coordinates
#' @keywords internal
cpp_apply_affine_chain <- function(coords, matrices) {
    .Call(`_neurotransform_cpp_apply_affine_chain`, coords, matrices)
}

#' Compute barycentric interpolation weights for surface mesh
#'
#' Projects points onto a triangular mesh and computes barycentric weights.
#'
#' @param coords Numeric matrix (N x 3) of query points
#' @param vertices Numeric matrix (V x 3) of mesh vertices
#' @param faces Integer matrix (F x 3) of face indices (0-based)
#' @return List with rows, cols, vals for sparse matrix construction
#' @keywords internal
cpp_barycentric_weights <- function(coords, vertices, faces) {
    .Call(`_neurotransform_cpp_barycentric_weights`, coords, vertices, faces)
}

#' Compute Jacobian matrices for a warp field at given coordinates
#'
#' Uses finite differences on the displacement field to compute 3x3 Jacobian
#' matrices at each query point.
#'
#' @param coords Numeric matrix (N x 3) of world coordinates
#' @param field Numeric vector of displacement values (flattened X x Y x Z x 3)
#' @param dim Integer vector of dimensions (X, Y, Z)
#' @param world_to_vox 4x4 world-to-voxel transform
#' @param vox_to_world 4x4 voxel-to-world transform (for scaling)
#' @return Numeric array (N x 3 x 3) of Jacobian matrices
#' @keywords internal
cpp_warp_jacobian <- function(coords, field, dim, world_to_vox, vox_to_world) {
    .Call(`_neurotransform_cpp_warp_jacobian`, coords, field, dim, world_to_vox, vox_to_world)
}

cpp_warp_jacobian_cubic <- function(coords, field, dim, world_to_vox, vox_to_world) {
    .Call(`_neurotransform_cpp_warp_jacobian_cubic`, coords, field, dim, world_to_vox, vox_to_world)
}

cpp_warp_jacobian_det_cubic <- function(coords, field, dim, world_to_vox, vox_to_world) {
    .Call(`_neurotransform_cpp_warp_jacobian_det_cubic`, coords, field, dim, world_to_vox, vox_to_world)
}

#' Compute Jacobian determinants for a warp field at given coordinates
#'
#' Efficiently computes only the determinants without full Jacobian matrices.
#'
#' @param coords Numeric matrix (N x 3) of world coordinates
#' @param field Numeric vector of displacement values (flattened X x Y x Z x 3)
#' @param dim Integer vector of dimensions (X, Y, Z)
#' @param world_to_vox 4x4 world-to-voxel transform
#' @param vox_to_world 4x4 voxel-to-world transform (for scaling)
#' @return Numeric vector of N determinants
#' @keywords internal
cpp_warp_jacobian_det <- function(coords, field, dim, world_to_vox, vox_to_world) {
    .Call(`_neurotransform_cpp_warp_jacobian_det`, coords, field, dim, world_to_vox, vox_to_world)
}

#' Apply a chain of affines and then a warp to coordinates (target -> source)
#'
#' @param coords Numeric matrix (n x 3) target world coords
#' @param affines List of 4x4 matrices (applied in order)
#' @param field Numeric vector displacement field (flattened 3 x X x Y x Z)
#' @param dim Integer vector (X,Y,Z)
#' @param world_to_vox 4x4 world-to-voxel matrix for the warp
#' @param cubic Logical; if TRUE use cubic warp sampling
#' @return Numeric matrix (n x 3) source world coords
#' @keywords internal
cpp_path_apply_affine_warp <- function(coords, affines, field, dim, world_to_vox, cubic) {
    .Call(`_neurotransform_cpp_path_apply_affine_warp`, coords, affines, field, dim, world_to_vox, cubic)
}

#' Apply affines -> warp -> affines to coordinates (target -> source)
#'
#' @param coords n x 3 target world coords
#' @param affines_pre list of 4x4 matrices applied before warp
#' @param field displacement field
#' @param dim field dims
#' @param world_to_vox warp world_to_vox
#' @param cubic use cubic sampling
#' @param affines_post list of 4x4 matrices applied after warp
#' @return n x 3 source world coords
cpp_path_apply_affine_warp_affine <- function(coords, affines_pre, field, dim, world_to_vox, cubic, affines_post) {
    .Call(`_neurotransform_cpp_path_apply_affine_warp_affine`, coords, affines_pre, field, dim, world_to_vox, cubic, affines_post)
}

#' Apply arbitrary steps (affine/warp) to coordinates (target -> source)
#'
#' @param coords n x 3 target world coords
#' @param steps list of steps with kind \"affine\" or \"warp\" and associated data
#' @return n x 3 transformed coords
cpp_path_apply_steps <- function(coords, steps) {
    .Call(`_neurotransform_cpp_path_apply_steps`, coords, steps)
}

cpp_make_resample_plan <- function(src_dim, src_coords_vox, method) {
    .Call(`_neurotransform_cpp_make_resample_plan`, src_dim, src_coords_vox, method)
}

cpp_apply_resample_plan <- function(plan_xptr, data, outside) {
    .Call(`_neurotransform_cpp_apply_resample_plan`, plan_xptr, data, outside)
}

#' Compute ribbon sampling weights for volume-to-surface projection
#'
#' Samples along cortical ribbon (inner to outer surface) and accumulates
#' trilinear interpolation weights.
#'
#' @param inner Inner surface coordinates (N x 3)
#' @param outer Outer surface coordinates (N x 3)
#' @param world_to_vox 4x4 world-to-voxel transform
#' @param dims Volume dimensions (3)
#' @param n_steps Number of samples along ribbon
#' @param mask Optional logical mask
#' @return List with rows, cols, vals for sparse matrix construction
#' @keywords internal
cpp_ribbon_weights <- function(inner, outer, world_to_vox, dims, n_steps, mask) {
    .Call(`_neurotransform_cpp_ribbon_weights`, inner, outer, world_to_vox, dims, n_steps, mask)
}

#' Sample a 3D volume at world coordinates
#'
#' Interpolates volume data at arbitrary world coordinates using the specified
#' interpolation method.
#'
#' @param data Numeric array (3D volume)
#' @param coords Numeric matrix (N x 3) of world coordinates
#' @param world_to_vox 4x4 world-to-voxel transform
#' @param method Interpolation method: "linear", "nearest", or "cubic"
#' @param outside Value for out-of-bounds locations
#' @return Numeric vector of N interpolated values
#' @keywords internal
cpp_sample_volume <- function(data, coords, world_to_vox, method, outside) {
    .Call(`_neurotransform_cpp_sample_volume`, data, coords, world_to_vox, method, outside)
}

#' Find nearest vertex for each query point
#'
#' @param coords Query coordinates (N x 3)
#' @param vertices Vertex coordinates (V x 3)
#' @return Integer vector of N vertex indices (1-based)
#' @keywords internal
cpp_nearest_vertex <- function(coords, vertices) {
    .Call(`_neurotransform_cpp_nearest_vertex`, coords, vertices)
}

#' Barycentric interpolation on surface mesh
#'
#' @param coords Query coordinates (N x 3)
#' @param vertices Mesh vertex coordinates (V x 3)
#' @param faces Face indices (F x 3, 1-based)
#' @param data Vertex data (V) or (V x K)
#' @return Interpolated values
#' @keywords internal
cpp_barycentric_sample <- function(coords, vertices, faces, data) {
    .Call(`_neurotransform_cpp_barycentric_sample`, coords, vertices, faces, data)
}

#' Ribbon sampling from volume onto surface
#'
#' Samples along cortical ribbon (inner to outer surface) and averages.
#'
#' @param data Volume data (3D array)
#' @param inner Inner surface coordinates (N x 3)
#' @param outer Outer surface coordinates (N x 3)
#' @param world_to_vox 4x4 world-to-voxel transform
#' @param n_steps Number of samples along ribbon
#' @param method Interpolation method
#' @return Numeric vector of N averaged values
#' @keywords internal
cpp_ribbon_sample_volume <- function(data, inner, outer, world_to_vox, n_steps, method) {
    .Call(`_neurotransform_cpp_ribbon_sample_volume`, data, inner, outer, world_to_vox, n_steps, method)
}

#' Fast triplet to dgCMatrix assembly with duplicate aggregation
#'
#' Converts triplet format (i, j, x) to sparse column matrix.
#'
#' @param i 1-based row indices
#' @param j 1-based col indices
#' @param x values
#' @param nrow number of rows
#' @param ncol number of cols
#' @param threads number of threads (unused currently)
#' @return dgCMatrix sparse matrix
#' @keywords internal
cpp_triplets_to_dgC <- function(i, j, x, nrow, ncol, threads = 1L) {
    .Call(`_neurotransform_cpp_triplets_to_dgC`, i, j, x, nrow, ncol, threads)
}

#' Apply warp displacement field to coordinates
#'
#' Fast C++ implementation of trilinear interpolation for displacement fields.
#'
#' @param coords Numeric matrix (N x 3) of world coordinates
#' @param field Numeric vector of displacement values (flattened 3 x X x Y x Z)
#' @param dim Integer vector of dimensions (X, Y, Z)
#' @param voxel_to_world 4x4 matrix (actually world_to_voxel inverse)
#' @return Numeric matrix (N x 3) of transformed coordinates
#' @keywords internal
cpp_apply_warp_field <- function(coords, field, dim, voxel_to_world) {
    .Call(`_neurotransform_cpp_apply_warp_field`, coords, field, dim, voxel_to_world)
}

cpp_apply_warp_field_cubic <- function(coords, field, dim, voxel_to_world) {
    .Call(`_neurotransform_cpp_apply_warp_field_cubic`, coords, field, dim, voxel_to_world)
}

#' Apply FNIRT B-spline coefficient field to coordinates
#'
#' Evaluates a cubic tensor-product B-spline coefficient field at query
#' coordinates in world space, returning transformed coordinates.
#'
#' @param coords Numeric matrix (N x 3) world coordinates
#' @param coeff Numeric vector of coefficients (flattened interleaved x,y,z)
#' @param dim Integer vector (X, Y, Z) control-grid dimensions
#' @param world_to_ctrl 4x4 world-to-control-grid affine
#' @return Numeric matrix (N x 3) transformed coordinates
#' @keywords internal
cpp_apply_bspline_coeff_field <- function(coords, coeff, dim, world_to_ctrl) {
    .Call(`_neurotransform_cpp_apply_bspline_coeff_field`, coords, coeff, dim, world_to_ctrl)
}

#' Compose two warp displacement fields
#'
#' Computes B then A composition for warp fields.
#'
#' @param fieldA Displacement field A (flattened)
#' @param dimA Dimensions of field A
#' @param world_to_voxA World-to-voxel transform for A
#' @param fieldB Displacement field B (flattened)
#' @param dimB Dimensions of field B
#' @param vox_to_worldB Voxel-to-world transform for B
#' @return List with composed field and dimensions
#' @keywords internal
cpp_compose_warp_fields <- function(fieldA, dimA, world_to_voxA, fieldB, dimB, vox_to_worldB) {
    .Call(`_neurotransform_cpp_compose_warp_fields`, fieldA, dimA, world_to_voxA, fieldB, dimB, vox_to_worldB)
}

#' Convert absolute-coordinate warp field to displacement field
#'
#' Converts a warp field storing absolute world coordinates to displacement field.
#'
#' @param field_abs Absolute coordinate field (flattened)
#' @param dim Field dimensions
#' @param vox_to_world Voxel-to-world affine
#' @return Displacement field
#' @keywords internal
cpp_absolute_to_displacement <- function(field_abs, dim, vox_to_world) {
    .Call(`_neurotransform_cpp_absolute_to_displacement`, field_abs, dim, vox_to_world)
}

#' Compute trilinear interpolation weights
#'
#' Given voxel coordinates, compute weights for 8 neighboring voxels.
#'
#' @param vox_coords Numeric matrix (N x 3) of voxel coordinates
#' @param dims Volume dimensions
#' @return List with rows, cols, vals for sparse matrix construction
#' @keywords internal
cpp_trilinear_weights <- function(vox_coords, dims) {
    .Call(`_neurotransform_cpp_trilinear_weights`, vox_coords, dims)
}

#' Generate world coordinates for full volume grid
#'
#' @param dim integer vector length 3
#' @param affine 4x4 voxel-to-world
#' @return Numeric matrix (N x 3) of world coordinates
#' @keywords internal
cpp_volume_world_coords <- function(dim, affine) {
    .Call(`_neurotransform_cpp_volume_world_coords`, dim, affine)
}

